### ISSUE TITLE
help for a scenario

### ISSUE THREAD

**Issue by rvxfahim** [arijitray1993/CARLA_tutorial#1]
Hello, 
I am just starting to play around with Carla and I was going through your tutorial.
Currently I am trying to build a scenario where I control a vehicle manually and spawn 3-4 more vehicles which will follow me, so that it forms a platoon.
To my understanding, I have to set autopilot true for the following vehicles and set their waypoints to my manually controlled vehicle. 
Seeking some guidance regarding making this happen, because I am confused about how to set a waypoint for a autopilot vehicle.
Any other methodology if you think is appropriate for this scenario, then your help will be much appreciated. 
Thanks in advance.

**Comment by arijitray1993** [comment]
Hi, 
You should be able to set the autopilot vehicle's waypoint by doing something like:
`autopilot_vehicle.set_transform(manual_vehicle.get_transform())` 

So, essentially, it's setting the location of the following vehicle to be the same as the manually driven vehicle. Haven't tried this myself, but I am assuming this (or something similar to this) will work. Good luck!
